### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kupiqu** [dschopf/qalculate#12]
this commit dc2a56191e2c8a5c71387acebc531d1042ad6855 (only enable interval support for libqalculate-2.2 or later) makes latte-dock crash

**Comment by kupiqu** [comment]
Same thing happens also in plasma, just checked

**Comment by kupiqu** [comment]
by the way I have libqalculate version 2.2.1:
```
-- Checking for module 'libqalculate>=0.9.8'
--   Found libqalculate, version 2.2.1
```

**Comment by dschopf** [comment]
I have been able to reproduce the crash but so far I don't understand what the problem seems to be.

**Comment by kupiqu** [comment]
might be this? it seems the only thing that is different for my library, isn't it?

```
@@ -353,6 +359,8 @@ void QWrapper::setNegativeBinaryTwosComplement(const bool value)
{
#if defined(HAVE_BINARY_TWOS_COMPLEMENT_OPTION)
  m_print_options.twos_complement = value;
+ #else
+   (void)value;
#endif
}

```

**Comment by kupiqu** [comment]
that's not it, I just checked :/

**Comment by dschopf** [comment]
Can you check if this is fixed now?

**Comment by kupiqu** [comment]
Fixed. Thank you
