### ISSUE TITLE
Provide deb package or PPA repository for debian/ubuntu linux with qalculate plasma widget

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#13]
Thanks for development, can you please provide compiled version of package for debian/ubuntu linux via .deb file of PPA repository, for easy install?

Here https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted is manual how to build auto-updated PPA via Launchpad recipe

**Comment by dschopf** [comment]
I will see what I can do, thanks for the hint with the manual.

**Comment by dschopf** [comment]
I have set up something for Ubuntu 18.04 (bionic) here: https://launchpad.net/~dschopf/+archive/ubuntu/plasma-applet-qalculate
So far it is untested, maybe you can give it a try. When I find some time I will try to add packages for other releases as well.

**Comment by MurzNN** [comment]
Great thanks! It installs successfully on Ubuntu 18.04, and works well!
But there are one problem in General tab of widget settings window:
![image](https://user-images.githubusercontent.com/336662/61198982-e9fdf600-a6e4-11e9-82ea-e4bdb69657cb.png)
Other tabs shows and works well.

Package `qml-module-qtquick-dialogs` is installed on my system, version is 5.9.5-0ubuntu1, file
`/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/libdialogplugin.so` is exists too.

Maybe Qalculate need newer version of module?

Also I ready to test your package on Ubuntu 19.04 version.

**Comment by dschopf** [comment]
I have just uploaded a new version which works on my Kubuntu 18.04 VM, could you check if it also works for you?

**Comment by MurzNN** [comment]
Yes, now it works well, thanks! Waiting for 19.04 version for use not only in old computers :)

**Comment by dschopf** [comment]
Package for disco (19.04) is now also available.

**Comment by MurzNN** [comment]
Can you please update PPA to recently released Ubuntu 19.10? Thanks!

**Comment by MurzNN** [comment]
Thanks, PPA now available here: https://launchpad.net/~plasma-applet-qalculate

- Qalculate! Plasma Applet Stable Releases: https://launchpad.net/~plasma-applet-qalculate/+archive/ubuntu/ppa
- Qalculate! Plasma Applet Daily Builds: https://launchpad.net/~plasma-applet-qalculate/+archive/ubuntu/daily
