### ISSUE TITLE
Input history not visible in widget

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#14]
I have default 500 history size and not check "Disable input history" in Settings, but can't see history in widget: 
![изображение](https://user-images.githubusercontent.com/336662/61517644-6871d500-aa10-11e9-8512-cea1e79a5940.png)
If I clean input field, press Down button - still nothing.
If history works, where it can be located and how to show it?

Also will be good to show recent history items always, for example 3 lines in bottom part of window, in format `2+2 = 4`.

**Comment by dschopf** [comment]
History uses the "up" key to go back (just like all shells I know). Please also note that only input which is confirmed with the "Enter" key will be appended to the history. If you use the live evaluation feature this does not support history.

**Comment by MurzNN** [comment]
Yes, `up` works (with live evaluation disabled, after pressing Enter). Will be good add to widget visible history lines, like in Qalculate full app, and even when live evaluation enabled - adds items to history via Enter button.

**Comment by kupiqu** [comment]
> even when live evaluation enabled - adds items to history via Enter button.

It actually works, but it has an issue, please see #29

**Comment by dschopf** [comment]
With v0.8 you can now actually see the history entries in a similar way as the KDE4 version showed them.
