### ISSUE TITLE
Currency converter not work like in full Qalculate app

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#15]
When I type same input "1dollar" in Qalculate app, and in widget, app shows me result as ruble, but widget shows strange string:
![изображение](https://user-images.githubusercontent.com/336662/61518116-8a1f8c00-aa11-11e9-8cc1-d1ee1ea1ca0f.png)

For `$1` input widget outputs `'$'`, for `1ruble` - `approx. 271828183 'r' nm^5`, etc.

How to fix this problem?

_P. S. Also can you please comment how to select output currency type in both Qalculate's? I always have rubles in output, but want to see dollars/euros too._

**Comment by MurzNN** [comment]
Also will be good to pre-select several currencies to convert in settings, eg for me I often converts to dollars, euro and rubles, so I input "5dollar" and want to see conversion to euro and rubles (2 results), if "5rubles" - euro and dollar, etc.

**Comment by dschopf** [comment]
Currency conversion should now work properly with 0.8.3. For the conversion into multiple currencies please use the "1dollar to RUB" etc. functionality.
