### ISSUE TITLE
Decrease font size for long results or split to lines

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#17]
At now long results are cuts by widget edge, here is example:
![изображение](https://user-images.githubusercontent.com/336662/61519110-c653ec00-aa13-11e9-945e-fabef6bef5ce.png)
Will be good to auto decrease size of result font, or split it to several lines.
Also, imho, default size of result font is too large, will be good to make it configurable.

**Comment by MurzNN** [comment]
Same problem for `pi` result:
![изображение](https://user-images.githubusercontent.com/336662/61519677-26975d80-aa15-11e9-8e8a-fc96f76ce955.png)

Also will be good to replace `approx.` to `~` symbol.

**Comment by dschopf** [comment]
Can you test if this works in the latest version?

**Comment by MurzNN** [comment]
Thanks, now it decreased well:
![image](https://user-images.githubusercontent.com/336662/68568602-11838600-046d-11ea-8933-3b0c947b028c.png)

**Comment by MurzNN** [comment]
Will be good to decrease padding of results line, because on smaller fonts it is too large:
![image](https://user-images.githubusercontent.com/336662/68569011-1e54a980-046e-11ea-81df-7571975cec40.png)

**Comment by dschopf** [comment]
This is not so easy because there is no real access to the actual text width. Instead I am using the average font width, which will look too small for narrow letters like l and i and too big for w or m. 
I did some research but I didn't find any better method to determine the scaling factor.
