### ISSUE TITLE
Timestamp auto detection and convert to human readable time

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#18]
Very often sysadmins and programmers need convert timestamp to human readable time. At now this is possible via function `unix2date(1563522554)`, but writing it each time is too long.

Will be good to implement feature (optionally) for auto-detect timestamp input (if input contains only 11 numbers) and execute this function automatically.

**Comment by dschopf** [comment]
Should be working with the latest version.

**Comment by MurzNN** [comment]
seems not work in plasma-applet-qalculate version 0.7.0-1~eoan with checked checkbox "Interpret 11 digit.." in settings with `1563522554` text:
![image](https://user-images.githubusercontent.com/336662/69789535-cd64e500-11d1-11ea-8196-0b5c580978f7.png)
but woks if I add additional number (`15635225540`) and show the future:
`среда, 17 июня 2465 г. 09:12:20 MSK`
Workaround is add leading zero to timestamp.
