### ISSUE TITLE
Default applet size is small with high dpi monitors

### ISSUE THREAD

**Issue by kupiqu** [dschopf/qalculate#2]
It would be great to have a way to make the applet bigger

**Comment by kupiqu** [comment]
There must be a better way, and having an option to specify it or a way to adjust it would be best, but for now I achieved a better size (x 3) by setting in FullRepresentation.qml:

```
  Layout.minimumHeight: 450
  Layout.minimumWidth: 600
```

**Comment by kupiqu** [comment]
This is what you need to adapt in FullRepresentation.qml to have a better default size for the applet (adapted from Milou applet):

```
import "../code/globals.js" as Globals # added line

Item {
  id: fullRepresentation

  property bool binary_enabled: plasmoid.configuration.binary && plasmoid.configuration.resultBase !== 2
  property bool octal_enabled: plasmoid.configuration.octal && plasmoid.configuration.resultBase !== 8
  property bool decimal_enabled: plasmoid.configuration.decimal && plasmoid.configuration.resultBase !== 10
  property bool hex_enabled: plasmoid.configuration.hexadecimal && plasmoid.configuration.resultBase !== 16

  anchors.fill: parent

  Layout.minimumWidth: Globals.PlasmoidWidth # modified line
  Layout.minimumHeight: Globals.PlasmoidWidth # modified line
```

and then create ../code/globals.js with:

```
// The Maximum and Minimum width of the Plasmoid
var PlasmoidWidth = units.gridUnit * 20;
```

**Comment by dschopf** [comment]
Ok I will give it a try.
Meanwhile you can use ALT + RightMouseButton to resize the plasmoid itself.

**Comment by kupiqu** [comment]
Ok, thanks

The problem of using ALT + RightMouseButton to resize is that one has to do it everytime plasma desktop reloads, so a good default setting would avoid dealing with that quite frequently.

**Comment by kupiqu** [comment]
It seems much easier than suggested above. Basically this change in FullRepresentation.qml would do it:

```
  // Layout.minimumHeight: 150
  // Layout.minimumWidth: 200
  Layout.minimumWidth: units.gridUnit * 20
  Layout.minimumHeight: units.gridUnit * 5
```

**Comment by dschopf** [comment]
37f8a19d2405aa267713d2d0ff1d4507f9d4dd9d should take care of this.
I am not sure but probably the font sizes also need to be scaled.
