### ISSUE TITLE
Recognize both symbols for number decimal separators

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#22]
Qalculate! full app recognize both symbols as decimal separators (`.` and `,`), example:
```
1.5*3 = 4,5
1,5*3 = 4,5
```
but plasma-applet-qalculate accepts only dot (`.`), and ignore `,` symbol:
```
1.5*3 = 4.5
1,5*3 = 45
```
Can you please fix this problem?

**Comment by dschopf** [comment]
The behavior you are describing only works if you set "Use comma as decimal separator" and not "Ignore dots in numbers". Otherwise these operations yield different results.

I guess I could provide the same options as well.

**Comment by MurzNN** [comment]
> The behavior you are describing only works if you set "Use comma as decimal separator" and not "Ignore dots in numbers".

Yes, this is default Qalculate! app settings. Thanks for implementing same options!

**Comment by dschopf** [comment]
This works for me with the latest release of libqalculate without any changes to the applet. Could you check this again?

**Comment by idamir** [comment]
Confirm, it works.

**Comment by MurzNN** [comment]
Hmm, for me it still doesn't work with current setup, but now shows the different result:
![image](https://user-images.githubusercontent.com/336662/164223437-f404f4f9-bb80-4762-b110-77b965f755bb.png)

And the same on full Qalculate app with default settings:
![image](https://user-images.githubusercontent.com/336662/164223680-334d11ef-c365-4fbb-8a7a-d9a644d0f243.png)

And on full app I can turn on the "Use comma as decimal separator" option to fix this, but plasmoid doesn't have such setting.

Maybe such results depend on locale? I have those settings:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=hy_AM
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=hy_AM
LC_NAME=hy_AM
LC_ADDRESS=hy_AM
LC_TELEPHONE=hy_AM
LC_MEASUREMENT=hy_AM
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by idamir** [comment]
Try this plasmoid setting:
![image](https://user-images.githubusercontent.com/4737692/164225483-bbd5c7e3-b2d1-4e1a-95c0-7f12e9a7c0c7.png)

**Comment by MurzNN** [comment]
Yeah, it works! And even with both variants - `1.5` and `1,5`, cool!
