### ISSUE TITLE
input history counter issue

### ISSUE THREAD

**Issue by kupiqu** [dschopf/qalculate#29]
I think there is an issue with history, in particular with the counter:

- Unless there are 2+ items saved, history is not displayed 
- Once there are 2+ items, history starts directly in the second most recent item (moving up in history). The workaround to get the most recent item is to move up and then down.

For the case it is important, I have live evaluation enabled in my system (and history items are saved by pressing Enter, as directed in settings).

**Comment by dschopf** [comment]
I am aware of several issues with the input history. It's next on my list of improvements, so please be a little bit patient.

**Comment by kupiqu** [comment]
Sure, thank you

**Comment by dschopf** [comment]
Issues should be fixed in v0.8.
