### ISSUE TITLE
default focus on text input

### ISSUE THREAD

**Issue by kupiqu** [dschopf/qalculate#3]
this is most useful if the applet is opened from a shortcut

**Comment by kupiqu** [comment]
actually, this seems to work now in my system

**Comment by kupiqu** [comment]
Ok, I see how I got confused.

Focus is right when clicking on the applet, but it is not when using the shortcut.

Wondering whether there is a way to have proper focus on shortcut as well...

**Comment by dschopf** [comment]
Yes, if you open the applet with the mouse the focus is correct.
But when you use the shortcut it does not work. I will probably ask the KDE guys if this is possible.

**Comment by kupiqu** [comment]
Great, thank you

**Comment by MurzNN** [comment]
On my Plasma 5.16.0 after activating widget via mouse it only remember previous focus (if I leave widget with active focus), but when I open widget via mouse at fist time - field is not focused.

Can you lookup code of `Application Menu` plasma widget? It have input box (Search) that have focus always - when activating widget via keyboard shortcut, and mouse too.

**Comment by dschopf** [comment]
Even though the input field is not highlighted the input should now be capture when the applet is activated either from the icon or the keyboard shortcut.

**Comment by kupiqu** [comment]
nice!
