### ISSUE TITLE
history improvements

### ISSUE THREAD

**Issue by kupiqu** [dschopf/qalculate#30]
It would be great to support the following two enhancements:

- history reset: remove all entries

- history edit: I ignore where history items are saved, but if in an external file, opening that file in the default text editor would be sufficient, so the user can manually remove undesired entries there, if wanted

**Comment by dschopf** [comment]
In the latest release you can find the path to the history file in the options. You may remove this file or edit it. Changes may require to restart the applet (log out and back in).
