### ISSUE TITLE
When pressing Ctrl+C - applet clears formula instead of copy to clipboard

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#33]
When I pressing <kbd>Ctrl+C</kbd> - applet clears current input field with formula, instead of copy it to clipboard without modifying. Can you please fix this?

**Comment by dschopf** [comment]
I thought this was already fixed in #25, apparently this is not the case. I will take a look.

**Comment by dschopf** [comment]
The issue is pretty embarassing, already fixed in master. I have found another bug I would like to fix before making a new release. Should not take too long.

**Comment by MurzNN** [comment]
Fixed, thanks!
