### ISSUE TITLE
Update PPA for Ubuntu 20.04

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#34]
Can you please update PPA for Ubuntu 20.04? Thanks!

**Comment by dschopf** [comment]
Which PPA are you using? This one should have a package for 20.04:

https://launchpad.net/~plasma-applet-qalculate/+archive/ubuntu/ppa

**Comment by dschopf** [comment]
Hmm, it looks like this is somehow outdated and does not work anymore. I will see if I can fix it.

**Comment by dschopf** [comment]
Look like the libqalculate21 dependency is pulling in some outdated libicu packages. Maybe @RogueScholar can help here?

**Comment by dschopf** [comment]
My personal PPA has been updated, disco is no longer supported. There are now packages of 0.8.1 for bionic, eoan and focal: https://launchpad.net/~dschopf/+archive/ubuntu/plasma-applet-qalculate/+packages

**Comment by MurzNN** [comment]
Yes, your personal PPA  works well (but with libqalculate20 instead of libqalculate21), I switched to it - thanks!
