### ISSUE TITLE
contents/ui/Qalculate.qml: ReferenceError: buttonIcon is not defined

### ISSUE THREAD

**Issue by idamir** [dschopf/qalculate#44]
The log has a lot of errors like
`file:///usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/Qalculate.qml:155: ReferenceError: buttonIcon is not defined`
`file:///usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/Qalculate.qml:131: ReferenceError: buttonIcon is not defined`

Indeed, buttonIcon is undefined. but is used 4 times in Qalculate.qml:
`   131              return Math.min(units.iconSizeHints.panel, parent.height) * buttonIcon.aspectRatio;`
`   141              return Math.min(units.iconSizeHints.panel, parent.width) * buttonIcon.aspectRatio;`
`   155              return Math.min(units.iconSizeHints.panel, parent.height) * buttonIcon.aspectRatio;`
`   165              return Math.min(units.iconSizeHints.panel, parent.width) * buttonIcon.aspectRatio;`

**Comment by dschopf** [comment]
Thanks for reporting this. Should now be fixed, can you test it?

**Comment by idamir** [comment]
Looks like it is really fixed. Close.
