### ISSUE TITLE
Currency AMD is not detected for conversion

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#45]
With full Qalculate app the expression `1000 AMD to USD` works well and shows results in $:
![image](https://user-images.githubusercontent.com/336662/160793166-234b19cf-02b4-4f26-913e-82319bc14221.png)

But in plasmoid - I see `'D''M' kA` in the results:
![image](https://user-images.githubusercontent.com/336662/160792602-341becc7-2370-4373-834c-5f32fdbcd88c.png)

Meanwhile `RUB` currency works well:
![image](https://user-images.githubusercontent.com/336662/160793003-42c02d3c-0332-4923-8b7b-2acf00da80ee.png)

Why this happens and how to fix it?

**Comment by dschopf** [comment]
I am not sure yet, it works fine for me
![Screenshot_20220330_183754](https://user-images.githubusercontent.com/3724829/160887027-a2c644ab-bb3f-4c4c-ab1c-c069971ca1bf.png)

Which version of the applet and libqalculate are you using?

**Comment by MurzNN** [comment]
Applet version 0.8.4, libqalculate21 version: 3.18.0-1

CLI version works well too:
```
$ qalc
> 100 AMD to USD

  100 × AMD ≈ $0.2054843781
```

**Comment by dschopf** [comment]
I still don't know how that can happen. Can you please go to the currency settings and check the list of available currencies in the "Change default currency" setting? Does AMD (֏) show up there?

Is that a binary version for Ubuntu or did you build it yourself?

**Comment by MurzNN** [comment]
That was strange thing, after upgrading to new Ubuntu version (and new qalculate package) - all becomes work well.
