### ISSUE TITLE
Add support for Ubuntu 22.04 Jammy Jellyfish to PPA 

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#47]
Ubuntu 22.04 Jammy Jellyfish is in RC stage from April 14 2022 and will be released at April 21 2022.
Will be good to add support for it into https://launchpad.net/~dschopf/+archive/ubuntu/plasma-applet-qalculate

**Comment by dschopf** [comment]
Package should now be available.

**Comment by MurzNN** [comment]
Thanks, it appears! But can't be installed because of wrong dependency:
```
$ sudo apt install plasma-applet-qalculate
The following packages have unmet dependencies:
 plasma-applet-qalculate : Depends: libqalculate21 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
In 22.04 there's a new version available - `libqalculate22`, can you fix this dependency?

**Comment by dschopf** [comment]
Sorry, I only built it and did not try to install it. Should be fixed pretty soon.

**Comment by MurzNN** [comment]
Now it installs successfully, thanks!
