### ISSUE TITLE
Cannot build 0.2

### ISSUE THREAD

**Issue by thegreyshadow** [dschopf/qalculate#5]
Using: Slackware64-current, Frameworks 5.33 and Plasma 5.9.5.

version 0.2 fails to build after following instructions. The relevant compilation output is pasted below:

```
[ 40%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin.cpp.o
[ 60%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o
/home/eduardo/Downloads/build/qalculate-0.2/plugin/qwrapper.cpp: In constructor ‘QWrapper::QWrapper(QObject*)’:
/home/eduardo/Downloads/build/qalculate-0.2/plugin/qwrapper.cpp:46:31: error: ‘bind’ is not a member of ‘std’
   m_thread = std::thread(std::bind(&QWrapper::worker, this));
                               ^~~~
/home/eduardo/Downloads/build/qalculate-0.2/plugin/qwrapper.cpp:46:31: note: suggested alternative: ‘find’
   m_thread = std::thread(std::bind(&QWrapper::worker, this));
                               ^~~~
                               find
make[2]: *** [plugin/CMakeFiles/plasmoidplugin.dir/build.make:87: plugin/CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:119: plugin/CMakeFiles/plasmoidplugin.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

Thanks for this plasmoid. It's great!! Hope that we can solve this as soon as possible.

**Comment by kupiqu** [comment]
This is surely because it requires libqalculate >=0.9.8. This stops me to update to 0.2 in KDE neon as well.

**Comment by kupiqu** [comment]
Mmm, it actually seems sth different, I double-checked  and I have other sort of errors... sorry for the noise.

**Comment by dschopf** [comment]
I just pushed some minor changes, could you please check if they fix this issue?

This error is not related to the version of libqalculate.

**Comment by thegreyshadow** [comment]
Just checked master and now qalculate-plasmoid builds and runs correctly without any apparent issues. Thanks!!

**Comment by dschopf** [comment]
OK, I will update to 0.2.1 to make this publicly available.
