### ISSUE TITLE
Cannot calculate the factors of a number

### ISSUE THREAD

**Issue by denilsonsa** [dschopf/qalculate#55]
If I try the `qalc` tool in the terminal, or qalculate-gtk or qalculate-qt, they all let me see the result of this expression: `55 to factors`

However, this plasma widget is failing the conversion. Look:

![Screenshot of the plasma widget with unexpected result](https://github.com/dschopf/plasma-applet-qalculate/assets/121676/a1c13eab-9050-4b6f-9266-a08863b3436b)

The same happens if I try something like `128 to hex`.

**Comment by dschopf** [comment]
I have checked the code for the tools you have mentioned and found that these commands are implemented manually and not part of the library. So in order for this to work I will have to implement this in my code as well. Not sure if this is worth the effort, especially the localization worries me a little bit here.

As a workaround for the "128 to hex" issue you could enable the hex output, which will always convert to hex in case the result is an integer. That way you could even save typing the "to hex".

**Comment by denilsonsa** [comment]
> these commands are implemented manually and not part of the library

I'm pretty new to Qalculate, and I myself don't even know where is a proper reference documentation of all the supported features. I didn't even know the feature set would be different for each application.

Do you know where is a good (official) up-to-date documentation of all the features supported by qalculate? It would be nice to link to it from the plasma applet. (EDIT: I found https://qalculate.github.io/manual/ but it's layout is somewhat annoying to use, and it's hard to trust that if some of the features are not available on all implementations)

Are there any other custom features implemented by those applications? Should we ask those features to be migrated to the qalculate library?

> As a workaround for the "128 to hex" issue you could enable the hex output

I've done that, thanks! Still not sure what is the workaround for getting the factors of a number.

Of course, no big deal. I appreciate your help and I appreciate your effort in building and sharing this plasma applet with the world. :)

**Comment by dschopf** [comment]
I will try to implement something, which will probably only work with the english "to factors".

**Comment by dschopf** [comment]
With the latest release v0.9.0 it should be supported to write `55 to factors`:
![Screenshot_20230808_124311](https://github.com/dschopf/plasma-applet-qalculate/assets/3724829/ad13272c-c6dc-448b-abe8-55ed38d69808)
