### ISSUE TITLE
Can't find a way to install (KDE 5 Plasma on Manjaro)

### ISSUE THREAD

**Issue by Ultome** [dschopf/qalculate#58]
I tried my best to follow the installation steps and the different READMEs from the different archives... I tried the "build from source" instructions, using the AUR package (`a failure occured in build`), downloading the archives and following the READMEs...

If someone can help... Thanks (I love Qalculate! and KRunner and this applet would be amazing on my laptop!)

**Comment by dschopf** [comment]
I'm sorry the install instructions did not work for you. To be honest they have not been updated for quite some time and may be outdated. 

In order to provide some support could you please provide some more details about your system, the steps you have executed and a detailed error message?

**Comment by Ultome** [comment]
I'm running Plasma 5 on Manjaro. I had some dependency missing. But once I fixed this, neither:
- the AUR install (`yay -Syu plasma5-applets-qalculate`);
- install from source:
  - in `/usr/lib` (or `lib64` which points to this dir);
  - nor in `/usr/lib32`...

... resulted in qalculate showing up in KRunner. It is nowhere to be found, even in KRunner settings...
I don't know if I'm doing this right... Can you help?

**Comment by dschopf** [comment]
Well, I have never tested on Manjaro, but that doesn't seem to be your problem.

Maybe there is a misunderstanding, but this is not a KRunner addon, this is a plasma widget. From a usage point of view I have never considered this, I think I would even have to remove some functionality to support this properly. Are you really looking for a KRunner integration of qalculate?

**Comment by dschopf** [comment]
And from what I can see here https://userbase.kde.org/Plasma/Krunner#Calculator, the existing Calculator KRunner addon already uses qalculate as a backend. Are you missing some features which are not supported by this addon?

**Comment by Ultome** [comment]
> Well, I have never tested on Manjaro, but that doesn't seem to be your problem.
> 
> Maybe there is a misunderstanding, but this is not a KRunner addon, this is a plasma widget. From a usage point of view I have never considered this, I think I would even have to remove some functionality to support this properly. Are you really looking for a KRunner integration of qalculate?

> And from what I can see here https://userbase.kde.org/Plasma/Krunner#Calculator, the existing Calculator KRunner addon already uses qalculate as a backend. Are you missing some features which are not supported by this addon?

Thanks for your answer. Just as you said, I thought it was a KRunner addon... But now that I know it's a widget, it works fine. Thanks for your time!
