### ISSUE TITLE
plasma 6

### ISSUE THREAD

**Issue by Cherkah** [dschopf/qalculate#59]
hey there,
thanks for your your with this applet.

Unfortunately the applet is not more so usefull without qt6 update.
can please update it? thanks

**Comment by dschopf** [comment]
I know, I'm already working on it but it needs a little more time.

**Comment by dschopf** [comment]
Changes for KF6 are done, you can test the changes in the Qt6 branch. I still want to make some minor changes before making a new official release.

**Comment by Cherkah** [comment]
@dschopf  thanks a lot for your work
