### ISSUE TITLE
[feature request] variable support

### ISSUE THREAD

**Issue by tubbadu** [dschopf/qalculate#63]
on the qalculate CLI I can assign variables using the `=` operator:

```
$ qalc
> myvar = 5

  save(5, myvar, Temporary, , 1) = 5

> 2*myvar

  2 × myvar = 10
```

This is not supported in the applet:

```
> myvar = 5
     0 / 0
> 2 * myvar
   2 ⋅ var() ⋅ y m
```

however, using the `save` syntax is supported:
```
> save(5, myvar, Temporary, , 1)
    5
> 2 * myvar
    10
```

the `=` operator is way easier to write, so it would be useful to add support for this also in the applet

**Comment by dschopf** [comment]
Never thought about that but it should not be too difficult to add this. I will check next week.

**Comment by dschopf** [comment]
Basic support for variable assignment is now in, at the moment there is no way to delete them.
