### ISSUE TITLE
issue in settings windows

### ISSUE THREAD

**Issue by Cherkah** [dschopf/qalculate#64]
hi
just need to see the attachment

![screenshot_24 07 24_18h32](https://github.com/user-attachments/assets/57e082ca-43cf-4db9-858a-2404c87a0523)

regards

Operating System: EndeavourOS 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.0-arch1-2 (64-bit)
Graphics Platform: Wayland

**Comment by Cherkah** [comment]
i forgot to mention the settings window doesn't take care of the system's locale (fr)

**Comment by dschopf** [comment]
UI issue should now be fixed.

For the French translation that is easy, there is none. Currently we only have a few, and French is none of them.
You can check here https://github.com/dschopf/plasma-applet-qalculate/tree/main/translate

I could ask ChatGPT to make a translation but I'm not sure that's such a great idea.

**Comment by Cherkah** [comment]
hoo really cool, that's what we call being reactive ;)
i'm waiting for the AUR package to be updated before taking advantage of it.

i'll try to provide the fr.po during the next week
cordially
