### ISSUE TITLE
can't build libplasmoidplugin.so

### ISSUE THREAD

**Issue by emezeta** [dschopf/qalculate#7]
Finally I chose to leave here this reply here, since desktop.org web app (or perhaps my own ignorance) prevented me from doing it there, sorry.

I built it all from source repositories
I tried qalculate-0.4.0 that time
Compiling any of both 2.0.0 or 2.4.0  libqalculate run smoothly with 

    ./autogen.sh (if needed)
    ./configure
    make
    make install (as root)

cmake::

  ~/setups/pkg/qalculate-0.4.0/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release   -DKDE_INSTALL_LIBDIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -- The C compiler identification is GNU 6.3.0
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for __GLIBC__
    -- Looking for __GLIBC__ - found
    -- Performing Test _OFFT_IS_64BIT
    -- Performing Test _OFFT_IS_64BIT - Success
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
    -- Found Readline: /usr/include
    -- Checking for module 'libqalculate>=0.9.8'
    --   Found libqalculate, version 2.0.0                                   <============   or 2.4.0 instead
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /_path_/setups/pkg/qalculate-0.4.0/build

then make::

 ~/setups/pkg/qalculate-0.4.0/build$ make
    Scanning dependencies of target org.kde.plasma.qalculate-metadata-json
    [ 16%] Generating org.kde.plasma.qalculate-metadata.json
    Unknown property type for key "X-KDE-ParentApp" -> falling back to string
    Unknown property type for key "X-Plasma-API" -> falling back to string
    Unknown property type for key "X-Plasma-MainScript" -> falling back to string
    Unknown property type for key "X-Plasma-RemoteLocation" -> falling back to string
    Generated  "/_path_/setups/pkg/qalculate-0.4.0/build/org.kde.plasma.qalculate-metadata.json"

    [ 16%] Built target org.kde.plasma.qalculate-metadata-json
    Scanning dependencies of target plasmoidplugin_automoc
    [ 33%] Automatic moc for target plasmoidplugin
    Generating moc source plasmoidplugin_automoc.dir/moc_plasmoidplugin_DZ66HZV5Z3E2K4.cpp
    Generating moc source plasmoidplugin_automoc.dir/moc_qwrapper_S2JPYLPKINLUVR.cpp
    Generating moc compilation plasmoidplugin_automoc.cpp
    [ 33%] Built target plasmoidplugin_automoc
    Scanning dependencies of target plasmoidplugin
    [ 50%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin.cpp.o
    [ 66%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o
    [ 83%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin_automoc.cpp.o
    [100%] Linking CXX shared library libplasmoidplugin.so
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::getExchangeRatesUpdateTime()':
    qwrapper.cpp:(.text+0x60e): undefined reference to `Calculator::getExchangeRatesTime()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::checkReturnState()':
    qwrapper.cpp:(.text+0x80c): undefined reference to `Calculator::aborted()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::printResultInBase(int, MathStructure&, QString&)':
    qwrapper.cpp:(.text+0xc3a): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::runCalculation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
    qwrapper.cpp:(.text+0x141c): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::worker()':
    qwrapper.cpp:(.text+0x2047): undefined reference to `Calculator::startControl(int)'
    qwrapper.cpp:(.text+0x205b): undefined reference to `Calculator::stopControl()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::QWrapper(QObject*)':
    qwrapper.cpp:(.text+0x2557): undefined reference to `Calculator::useDecimalPoint(bool)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::fileDownloaded(QNetworkReply*)':
    qwrapper.cpp:(.text+0x2c6a): undefined reference to `Calculator::getExchangeRatesTime()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::setDecimalSeparator(QString const&)':
    qwrapper.cpp:(.text+0x261): undefined reference to `Calculator::useDecimalPoint(bool)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `_GLOBAL__sub_I_qwrapper.cpp':
    qwrapper.cpp:(.text.startup+0x33f): undefined reference to `Number::Number(long, long, long)'
    collect2: error: ld returned 1 exit status
    plugin/CMakeFiles/plasmoidplugin.dir/build.make:147: recipe for target 'plugin/libplasmoidplugin.so' failed
    make[2]: *** [plugin/libplasmoidplugin.so] Error 1
    CMakeFiles/Makefile2:155: recipe for target 'plugin/CMakeFiles/plasmoidplugin.dir/all' failed
    make[1]: *** [plugin/CMakeFiles/plasmoidplugin.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

finally "make install"

 ~/setups/pkg/qalculate-0.4.0/build$ su -c "make install"
    Password: 
    [ 16%] Built target org.kde.plasma.qalculate-metadata-json
    [ 33%] Automatic moc for target plasmoidplugin
    [ 33%] Built target plasmoidplugin_automoc
    [ 50%] Linking CXX shared library libplasmoidplugin.so
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::updateExchangeRates()':
    qwrapper.cpp:(.text+0x4af): undefined reference to `Calculator::getExchangeRatesUrl[abi:cxx11](int)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::getExchangeRatesUpdateTime()':
    qwrapper.cpp:(.text+0x60e): undefined reference to `Calculator::getExchangeRatesTime()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::checkReturnState()':
    qwrapper.cpp:(.text+0x80c): undefined reference to `Calculator::aborted()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::printResultInBase(int, MathStructure&, QString&)':
    qwrapper.cpp:(.text+0xc73): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::runCalculation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
    qwrapper.cpp:(.text+0x145c): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::worker()':
    qwrapper.cpp:(.text+0x2087): undefined reference to `Calculator::startControl(int)'
    qwrapper.cpp:(.text+0x209b): undefined reference to `Calculator::stopControl()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::QWrapper(QObject*)':
    qwrapper.cpp:(.text+0x25c8): undefined reference to `Calculator::useDecimalPoint(bool)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::fileDownloaded(QNetworkReply*)':
    qwrapper.cpp:(.text+0x2b6b): undefined reference to `Calculator::getExchangeRatesFileName[abi:cxx11](int)'
    qwrapper.cpp:(.text+0x2ce2): undefined reference to `Calculator::getExchangeRatesTime()'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::setDecimalSeparator(QString const&)':
    qwrapper.cpp:(.text+0x261): undefined reference to `Calculator::useDecimalPoint(bool)'
    CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `_GLOBAL__sub_I_qwrapper.cpp':
    qwrapper.cpp:(.text.startup+0x37b): undefined reference to `Number::Number(long, long, long)'
    collect2: error: ld returned 1 exit status
    plugin/CMakeFiles/plasmoidplugin.dir/build.make:147: recipe for target 'plugin/libplasmoidplugin.so' failed
    make[2]: *** [plugin/libplasmoidplugin.so] Error 1
    CMakeFiles/Makefile2:155: recipe for target 'plugin/CMakeFiles/plasmoidplugin.dir/all' failed
    make[1]: *** [plugin/CMakeFiles/plasmoidplugin.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

Not significative output differences compiling with any of 2.0.0 or 2.4.0 versions of libqalculate for 'make' and 'make install' commands. { references like (.text+0x2c6a) and percent compiling advances as sole differs. ]

**Comment by dschopf** [comment]
This still looks like a version mismatch between your header and library files for libqalculate.
Can you try to run "./configure --prefix=/usr" when installing libqalculate? Maybe this will overwrite some old lingering library version on your system.

**Comment by emezeta** [comment]
I guess libqalculate should works at /usr/local too. However I redo "./configure --prefix=/usr", "make" & "su -c make install" as your suggest. It runs fine as usually. It is at place now
```
~/setups/pkg/qalculate-0.4.0/build$ ls /usr/lib/libqalculate.* -l
-rw-r--r-- 1 root root 46288704 Apr 27 10:32 /usr/lib/libqalculate.a
-rwxr-xr-x 1 root root     1057 Apr 27 10:32 /usr/lib/libqalculate.la
lrwxrwxrwx 1 root root       22 Apr 27 10:32 /usr/lib/libqalculate.so -> libqalculate.so.16.0.0
lrwxrwxrwx 1 root root       22 Apr 27 10:32 /usr/lib/libqalculate.so.16 -> libqalculate.so.16.0.0
-rwxr-xr-x 1 root root 17993496 Apr 27 10:32 /usr/lib/libqalculate.so.16.0.0
```
Then 
```
~/setups/pkg$ rm -rf ~/setups/pkg/qalcutalte-0.4.0
~/setups/pkg$ unzip qalcutalte-0.4.0.zip
Archive:  qalculate-0.4.0.zip
78898d7b7e8b71337c68423b68e875fa013f8e9b
   creating: qalculate-0.4.0/
 extracting: qalculate-0.4.0/.gitignore
``` 
... etc. ...
```
~/setups/pkg/$ mkdir -p ~/setups/pkg/qalculate-0.4.0/build
~/setups/pkg/$ cd  ~/setups/pkg/qalculate-0.4.0/build
~/setups/pkg/qalculate-0.4.0/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
           -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib \
           -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found Readline: /usr/include  
-- Checking for module 'libqalculate>=0.9.8'
--   Found libqalculate, version 2.4.0
-- Configuring done
-- Generating done
-- Build files have been written to: /_path_/setups/pkg/qalculate-0.4.0/build
```
and
```
~/setups/pkg/qalculate-0.4.0/build$ make
Scanning dependencies of target org.kde.plasma.qalculate-metadata-json
[ 16%] Generating org.kde.plasma.qalculate-metadata.json
Unknown property type for key "X-KDE-ParentApp" -> falling back to string
Unknown property type for key "X-Plasma-API" -> falling back to string
Unknown property type for key "X-Plasma-MainScript" -> falling back to string
Unknown property type for key "X-Plasma-RemoteLocation" -> falling back to string
Generated  "/_my_home_path_/setups/pkg/qalculate-0.4.0/build/org.kde.plasma.qalculate-metadata.json"

[ 16%] Built target org.kde.plasma.qalculate-metadata-json
Scanning dependencies of target plasmoidplugin_automoc
[ 33%] Automatic moc for target plasmoidplugin
Generating moc source plasmoidplugin_automoc.dir/moc_plasmoidplugin_DZ66HZV5Z3E2K4.cpp
Generating moc source plasmoidplugin_automoc.dir/moc_qwrapper_S2JPYLPKINLUVR.cpp
Generating moc compilation plasmoidplugin_automoc.cpp
[ 33%] Built target plasmoidplugin_automoc
Scanning dependencies of target plasmoidplugin
[ 50%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin.cpp.o
[ 66%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o
[ 83%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin_automoc.cpp.o
[100%] Linking CXX shared library libplasmoidplugin.so
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::updateExchangeRates()':
qwrapper.cpp:(.text+0x4af): undefined reference to `Calculator::getExchangeRatesUrl[abi:cxx11](int)'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::getExchangeRatesUpdateTime()':
qwrapper.cpp:(.text+0x60e): undefined reference to `Calculator::getExchangeRatesTime()'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::checkReturnState()':
qwrapper.cpp:(.text+0x80c): undefined reference to `Calculator::aborted()'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::printResultInBase(int, MathStructure&, QString&)':
qwrapper.cpp:(.text+0xc73): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::runCalculation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
qwrapper.cpp:(.text+0x145c): undefined reference to `Calculator::print[abi:cxx11](MathStructure const&, int, PrintOptions const&)'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::worker()':
qwrapper.cpp:(.text+0x2087): undefined reference to `Calculator::startControl(int)'
qwrapper.cpp:(.text+0x209b): undefined reference to `Calculator::stopControl()'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::QWrapper(QObject*)':
qwrapper.cpp:(.text+0x25c8): undefined reference to `Calculator::useDecimalPoint(bool)'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::fileDownloaded(QNetworkReply*)':
qwrapper.cpp:(.text+0x2b6b): undefined reference to `Calculator::getExchangeRatesFileName[abi:cxx11](int)'
qwrapper.cpp:(.text+0x2ce2): undefined reference to `Calculator::getExchangeRatesTime()'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `QWrapper::setDecimalSeparator(QString const&)':
qwrapper.cpp:(.text+0x261): undefined reference to `Calculator::useDecimalPoint(bool)'
CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o: In function `_GLOBAL__sub_I_qwrapper.cpp':
qwrapper.cpp:(.text.startup+0x37b): undefined reference to `Number::Number(long, long, long)'
collect2: error: ld returned 1 exit status
plugin/CMakeFiles/plasmoidplugin.dir/build.make:147: recipe for target 'plugin/libplasmoidplugin.so' failed
make[2]: *** [plugin/libplasmoidplugin.so] Error 1
CMakeFiles/Makefile2:155: recipe for target 'plugin/CMakeFiles/plasmoidplugin.dir/all' failed
make[1]: *** [plugin/CMakeFiles/plasmoidplugin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Finally ` su -c "make install" ` fail as well
and thanks a lot for the time you spend helping

**Comment by dschopf** [comment]
There must be another outdated library somewhere on your system.
What does `locate libqalculate.so` or `find / -name "libqalculate.so*"` show?
If there are no other libs anywhere please provide the output of 
`nm -CD /usr/lib/libqalculate.so | c++filt | grep aborted`
Finally it might be helpful to see the linker command with `make VERBOSE=1` in the qalculate-0.4.0/build folder.

**Comment by emezeta** [comment]
There was no bug at all in your code. Effectively I had a pretty mix of versions for libqalculate.
Once I had put a little cleaning and order in my library installation everything has worked fine.
Thank you very much for helping me.
