### ISSUE TITLE
Error on any calculation

### ISSUE THREAD

**Issue by xpt3** [dschopf/qalculate#8]
The plasmoid doesn't give me results, only "Error" as result. I don't have errors in the compilation and qalculate-gtk works fine. I tried in 2 computers and the result is the same.

Distribution: Archlinux  (updated)
Plasma 5.12.5
gcc 8.1.0
libqalculate 2.5.0

`$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON`
> -- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Checking for module 'libqalculate'
--   Found libqalculate, version 2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Descargas/qalculate-master/build

`$ make`
>Scanning dependencies of target org.kde.plasma.qalculate-plasmoids-metadata-json
[ 16%] Generating org.kde.plasma.qalculate-plasmoids-metadata.json
About to parse service type file "/usr/share/kservicetypes5/plasma-applet.desktop"
Found property definition "X-Plasma-API" with type "QString"
Found property definition "X-Plasma-RootPath" with type "QString"
Found property definition "X-Plasma-MainScript" with type "QString"
Found property definition "X-Plasma-ContainmentType" with type "QString"
Found property definition "X-Plasma-DropMimeTypes" with type "QStringList"
Found property definition "X-Plasma-DropUrlPatterns" with type "QStringList"
Found property definition "X-Plasma-NotificationArea" with type "QString"
Found property definition "X-Plasma-NotificationAreaCategory" with type "QString"
Found property definition "X-Plasma-DBusActivationService" with type "QString"
Found property definition "X-KDE-ParentApp" with type "QString"
Found property definition "X-Plasma-Provides" with type "QStringList"
Found property definition "X-Plasma-PreloadWeight" with type "int"
Found property definition "X-Plasma-ConfigPlugins" with type "QStringList"
Found property definition "X-Plasma-StandAloneApp" with type "bool"
Found property definition "X-Plasma-RequiredExtensions" with type "QStringList"
Found property definition "NoDisplay" with type "bool"
Unknown property type for key "X-Plasma-RemoteLocation" -> falling back to string
Generated  "/home/user/Descargas/qalculate-master/build/org.kde.plasma.qalculate-plasmoids-metadata.json" 
[ 16%] Built target org.kde.plasma.qalculate-plasmoids-metadata-json
Scanning dependencies of target plasmoidplugin_autogen
[ 33%] Automatic MOC for target plasmoidplugin
[ 33%] Built target plasmoidplugin_autogen
Scanning dependencies of target plasmoidplugin
[ 50%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin.cpp.o
[ 66%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/qwrapper.cpp.o
[ 83%] Building CXX object plugin/CMakeFiles/plasmoidplugin.dir/plasmoidplugin_autogen/mocs_compilation.cpp.o
[100%] Linking CXX shared library libplasmoidplugin.so
[100%] Built target plasmoidplugin
Scanning dependencies of target translations
[100%] Built target translations

`$ sudo make install`
> [ 16%] Built target org.kde.plasma.qalculate-plasmoids-metadata-json
[ 33%] Automatic MOC for target plasmoidplugin
[ 33%] Built target plasmoidplugin_autogen
[100%] Built target plasmoidplugin
[100%] Built target translations
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/images
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/images/Qalculate.svg
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/QWrapper.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/FullRepresentation.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/Qalculate.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/CompactRepresentation.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/config
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/config/Input.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/config/Currency.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/config/Output.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/ui/config/General.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/config
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/contents/config/config.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/metadata.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.plasma.qalculate/metadata.json
-- Installing: /usr/share/metainfo/org.kde.plasma.qalculate.appdata.xml
-- Up-to-date: /usr/share/kservices5/plasma-applet-org.kde.plasma.qalculate.desktop
-- Installing: /usr/lib/qt/qml/org/kde/private/qalculate/libplasmoidplugin.so
-- Up-to-date: /usr/lib/qt/qml/org/kde/private/qalculate/qmldir
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.plasma.qalculate.mo
-- Installing: /usr/share/locale/en/LC_MESSAGES/plasma_applet_org.kde.plasma.qalculate.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.plasma.qalculate.mo`

**Comment by dschopf** [comment]
I do have the same system, so in theory it should work without any issues.
Can you post the output of the following two commands:
```
ldd /usr/lib/qt/qml/org/kde/private/qalculate/libplasmoidplugin.so
plasmoidviewer --applet org.kde.plasma.qalculate
```
Maybe it also helps if you post a screenshot of the "Error" state of the plasmoid.

**Comment by xpt3** [comment]
`ldd /usr/lib/qt/qml/org/kde/private/qalculate/libplasmoidplugin.so`
`ldd: /usr/lib/qt/qml/org/kde/private/qalculate/libplasmoidplugin.so: No such file or directory`

It was a permissions problem. I didn't have permissions to access the folder /usr/lib/qt/qml/org/kde/private/qalculate/ 

Changing the permissions was fixed.

Thanks
